
services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: php-demo
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
    environment:
      # đặt tên server để IDE map (PHPStorm, VSCode)
      PHP_IDE_CONFIG: "serverName=php-docker"

      # Mặc định: TẮT Xdebug cho đỡ nặng
      XDEBUG_MODE: "off"

      # Xdebug sẽ dùng host.docker.internal để kết nối về Mac
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-demo
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: mysql:8.4
    container_name: mysql-demo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command:
      - --mysql-native-password=ON
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  dbdata: